name: Configure Customer Bot
on:
  repository_dispatch:
    types: [customer-event]
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Full Payload
        run: echo "Full payload: ${{ toJSON(github.event) }}"
      - name: Validate Payload
        uses: actions/github-script@v6
        with:
          script: |
            const payload = github.event.client_payload || {};
            console.log("Client payload:", JSON.stringify(payload));
            if (!payload.slug || !payload.associate_id || !payload.associate_name) {
              throw new Error('Missing required fields in client_payload: slug, associate_id, associate_name. Received: ' + JSON.stringify(payload));
            }
            console.log("Validated payload: slug=%s, associate_id=%s, associate_name=%s", payload.slug, payload.associate_id, payload.associate_name);
