.github/workflows/customer-bot-config.yml
Update customer-bot-config.ymlUpdate customer-bot-config.yml with enh… #14
Jobs
Run details
Triggered via push 10 minutes ago
@HealthylifestyleservicesHealthylifestyleservices
pushed
 c65d030
main
Status
Failure
Total duration
–
Artifacts
–
This workflow graph cannot be shown
A graph will be generated the next time this workflow is run.

Annotations
1 error
Invalid workflow file: .github/workflows/customer-bot-config.yml#L12
You have an error in your yaml syntax on line 12
No response.

Grok was unable to finish replying.
Please try again later or use a different model.

How can Grok help?
